# Generated by Django 5.2.11 on 2026-02-15 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(choices=[('backend', 'Backend Developer'), ('frontend', 'Frontend Developer'), ('android', 'Android Developer'), ('ml', 'Machine Learning Engineer'), ('data', 'Data Analyst')], max_length=50)),
                ('experience_level', models.CharField(choices=[('fresher', 'Fresher'), ('junior', '1-3 Years'), ('mid', '3-5 Years'), ('senior', '5+ Years')], max_length=50)),
                ('company_type', models.CharField(choices=[('startup', 'Startup'), ('product', 'Product Based'), ('service', 'Service Based'), ('faang', 'FAANG')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.resume')),
            ],
        ),
    ]
