# Generated by Django 5.2.11 on 2026-02-20 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_generatedresume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalysis',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.resume'),
        ),
    ]
